GET http://localhost:3003/actor/"Tony Ramos"

####

GET http://localhost:3003/actor?gender="female"

####

PUT http://localhost:3003/actor/001
Content-Type: application/json

{ "salary": 472650 }

####

DELETE http://localhost:3003/actor/006
Content-Type: application/json

####

GET http://localhost:3003/actor?gender&salary
Content-Type: application/json
